#+TITLE: Requirements for Footer Service
#+AUTHOR: VLEAD
#+DATE: [2017-04-11 Wed]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ../org-templates/level-1.org
#+options: ^:nil
#+LATEX: Literal LaTeX code for export

* Introduction 
  The requirements of =Footer Service= are listed here.


* Ability of the user of =Virtual Labs= to provide feedback
  A user is provided with a feedback form with:
  - a set of questions and
  - an ability to answer these questions.


:PROPERTIES:
:CUSTOM_ID: provide_feedback
:END: 
** Feedback 
:PROPERTIES:
:CUSTOM_ID: feedback
:END: 
   A user is able to provide feedback after conducting an experiment.

  Realized in data model as [[../data-model/index.org::#entity_feedback][Feedback]]
** Questions
:PROPERTIES:
:CUSTOM_ID: questions
:END: 
   The feedback form consists of a set of questions

  Realized in data model as [[../data-model/index.org::#entity_question][Question]]
** Answers
:PROPERTIES:
:CUSTOM_ID: answers
:END: 
   The user either chooses an option or a set a options or types text for the
   questions posed. 

  Realized in data model as [[../data-model/index.org::#entity_answer][Answer]]
** User Responses
:PROPERTIES:
:CUSTOM_ID: user_responses
:END: 
   The ability to pair the answer with the question for analysis is provided by
   the feedback service.
  Realized in data model as [[../data-model/index.org::#entity_responses][Response]]

* Capture =Workshop Usage= via feedback forms
:PROPERTIES:
:CUSTOM_ID: workshop_usage
:END: 
  A =Nodal Center Coordinator= is able to view the usage from a workshop.  The
  workshop usage is defined as the number of feedback forms submitted by the
  students attending the workshop.

  Realized in design as [[../design/index.org::#workshop_usage][Capturing workshop usage through feedback forms]]

* Analytics
:PROPERTIES:
:CUSTOM_ID: analytics
:END: 
  Provide an API to dump the data from outreach service to an elastic
  search engine

  Realized in design as [[../design/index.org::#dump_to_elastic_search][Dump to Elastic Search]]

* COMMENT Review Comments


